repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.12
  hooks:
  - id: ruff
  - id: ruff

- repo: https://github.com/google/pyink
  rev: 24.10.1
  hooks:
  - id: pyink
    name: Format code with Pyink
    additional_dependencies: []
    args: ["--config", "pyproject.toml", "."]

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.17.1
#     hooks:
#     -   id: mypy
