name: fir

ngpus: 4

training:
  batch_size: 64
  accum: 2

eval:
  batch_size: 64
  perplexity_batch_size: 32

processing:
  num_proc_train: 40
  num_proc_valid: 40

loader:
  train_num_workers: 4
  eval_num_workers: 4
  pin_memory: true
  persistent_workers: true

hydra:
  launcher:
    max_num_timeout: 100000
    # timeout_min: 10079
    partition: g40x
    account: stanford
    mem_gb: 96
    cpus_per_task: 40
    gpus_per_node: ${worker.ngpus}
    constraint: null
